In [1]:
import numpy as np # linear algebra 
import pandas as pd # data processing

In [4]:
mkdir data

In [11]:
df = pd.read_csv("/kaggle/input/housing/housing.csv")

In [12]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [13]:
pd.__version__


'2.0.3'

In [18]:
df.shape

(20640, 10)

In [29]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [36]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [40]:
df['median_house_value'].mean()

206855.81690891474

In [43]:
df[df['ocean_proximity'] == "NEAR BAY"]['median_house_value'].mean()

259212.31179039303

In [53]:
tbmean= df['total_bedrooms'].mean()
tbmean

537.8705525375618

In [55]:
df['tbnew']= df['total_bedrooms'].fillna(tbmean)
# df['tbnew'].isna().sum()
df['tbnew'].mean()

537.8705525375617

In [56]:
islanddf= df[df['ocean_proximity'] == 'ISLAND']
X= islanddf[['housing_median_age', 'total_rooms', 'total_bedrooms']] 
X

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [57]:
X1 = X.to_numpy()
X1.shape

(5, 3)

In [58]:
X1

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [59]:
T= X1.transpose()
T.shape

(3, 5)

In [60]:
T

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [61]:
XTX= np.dot(T, X1)
XTX


array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [62]:
inv= np.linalg.inv(XTX)
z= np.dot(inv, T)
z

array([[-0.00825608, -0.00653208, -0.00232159,  0.02565144,  0.01204934],
       [-0.00165852,  0.0011141 ,  0.00139656, -0.00103215, -0.00110698],
       [ 0.00754365, -0.00301964, -0.00455125,  0.00181685,  0.00329418]])

In [63]:
y= np.array([950, 1300, 800, 1000, 1300])
w= np.dot(z,y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [64]:
w[-1]

5.699229455065586